### ISSUE TITLE
ComfyUI-Flux-Inpainting：expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Aiseng-sketch** [rubi-du/ComfyUI-Flux-Inpainting#1]
File "E:\ComfyUI_GUANFANG\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\clip\tokenization_clip.py", line 306, in __init__                                                                                     
    with open(vocab_file, encoding="utf-8") as vocab_handle:                                                            
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                             
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by rubi-du** [comment]
@Aiseng-sketch Can you provide a specific ComfyUI workflow to help us better pinpoint the issue

**Comment by Aiseng-sketch** [comment]
[inpainting1.json](https://github.com/user-attachments/files/18149411/inpainting1.json)
Thank you, boss.

**Comment by rubi-du** [comment]
@Aiseng-sketch This issue should be due to missing or incorrect model files. You can download the model as described in Readme and try again
link：https://github.com/rubi-du/ComfyUI-Flux-Inpainting?tab=readme-ov-file#models
<img width="867" alt="image" src="https://github.com/user-attachments/assets/a8c30ef9-65d4-48bc-a799-88e5d43fe8b7" />

**Comment by Aiseng-sketch** [comment]
It's solved. Thank you, big brother.

**Comment by rubi-du** [comment]
> It's solved. Thank you, big brother.

My pleasure. If you have any other questions, please feel free to raise them. so I will close this issue later.
